### ISSUE TITLE
Would you please make some comparison with another similar channel pruning work by Megvii?

### ISSUE THREAD

**Issue by hungsing92** [Roll920/ThiNet#7]
Hi,

Many thanks for your excellent work!!!

I found another [ICCV paper ](http://openaccess.thecvf.com/content_ICCV_2017/papers/He_Channel_Pruning_for_ICCV_2017_paper.pdf)similiar with your work.  
Would you please make some comment on this paper?

Best,
hungsing

**Comment by Roll920** [comment]
@hungsing92 This paper has a very similar idea with our ThiNet. The only difference is the method used for channel selection. They proposed a lasso based algorithm, while ours are greedy-based. Hence, these two papers have very similar performances.
